#!/bin/bash
#SBATCH --job-name=train_NPA
#SBATCH --output=train_mind_NPA_%j.out
#SBATCH --error=train_mind_NPA_%j.err
#SBATCH --time=10:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=32
#SBATCH --gres=gpu:1
#SBATCH --constraint=gpunode

source /var/scratch/zta207/miniconda3/etc/profile.d/conda.sh
conda activate xfair

module load cuda11.7/toolkit/11.7

cd /home/zta207/xnrs

python train.py --config config/mind_small_NPA.yml
