#!/bin/bash
#SBATCH --job-name=train_mind
#SBATCH --output=train_mind_%j.out
#SBATCH --error=train_mind_%j.err
#SBATCH --time=10:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=32
#SBATCH --gres=gpu:1
#SBATCH --nodelist=node206


source /var/scratch/zta207/miniconda3/etc/profile.d/conda.sh
conda activate xfair

module load cuda11.7/toolkit/11.7


cd /home/zta207/xnrs

python train.py --config config/mind_small.yml
