#!/bin/bash
#SBATCH --job-name=train_mind
#SBATCH --output=test_CL_theme_tsne_%j.out
#SBATCH --error=test_CL_theme_tsne_%j.err
#SBATCH --time=24:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=32
#SBATCH --gres=gpu:1
#SBATCH --mem=60G
#SBATCH --constraint=gpunode

source /var/scratch/zta207/miniconda3/etc/profile.d/conda.sh
conda activate xfair

module load cuda11.7/toolkit/11.7


cd /home/zta207/xnrs

python train.py --config config/mind_small_CL.yml
