# data:
dataset: mind
train_news_data_path: /var/scratch/zta207/data/MINDsmall_train/news_full_smpnet.pkl
train_user_data_path: /var/scratch/zta207/data/MINDsmall_train/behaviors4.csv
test_news_data_path: /var/scratch/zta207/data/MINDsmall_dev/news_full_smpnet.pkl
test_user_data_path: /var/scratch/zta207/data/MINDsmall_dev/behaviors4.csv
min_hist_len: 1

# model:
model: 'NPA'
base_model: 'NPA'
scoring: 'dot'
text_features: ['title_emb']
catg_features: []
user_features: ['user_index']
add_features: []
n_users: 703789
user_emb_dim: 64  #  unique 
title_emb_dim: 256
total_emb_dim: 256
# cat_emb_dim: 16
# sub_emb_dim: 16
d_backbone: 768
hist_len: 25
st_hist_len: 25
seq_len: 50
p_dropout: 0.
bias: False
backbone: 'sentence-transformers/all-mpnet-base-v2'


# training:
num_workers: 0
n_negatives: 4
batch_size: 64
shuffle_data: True
n_epochs: 10
test_freq: 1
ckpt_freq: 1
device: 'cuda:0'
lr: 0.0001
random_seed: 0
# random_seed: 1
# random_seed: 8
apply_sigmoid: False
load_article_ids: False
contrastive_temperature: 0.08
contrastive_lambda: 0.1

# logging:
wandb: False
mode: offline
project: xnrs
tags: [mind, npa]
name: mind_small_npa
dir: /var/scratch/zta207/experiments
notes: NPA model on MIND small dataset with full features
