# data:
dataset: mind
train_news_data_path: /var/scratch/zta207/data/MINDsmall_train/news_full_smpnet.pkl
train_user_data_path: /var/scratch/zta207/data/MINDsmall_train/behaviors4.csv
test_news_data_path: /var/scratch/zta207/data/MINDsmall_dev/news_full_smpnet.pkl
test_user_data_path: /var/scratch/zta207/data/MINDsmall_dev/behaviors4.csv
min_hist_len: 1

# model:
model: 'NRMS'
base_model: 'NRMS'
# smallNAML
scoring: 'dot'
text_features: ['title_emb'] # 'abstract_emb'
# catg_features: ['category_index', 'subcategory_index']
n_categories: 19
n_subcategories: 300
# n_users: 50000
n_users: 703789
n_heads: 16
user_features: []
add_features: []
title_emb_dim: 256
total_emb_dim: 256
# total_emb_dim: 272
cat_emb_dim: 16
sub_emb_dim: 16
d_backbone: 768
hist_len: 25
st_hist_len: 25
seq_len: 50
p_dropout: 0.
bias: False
backbone: 'sentence-transformers/all-mpnet-base-v2'

# training:
num_workers: 0
n_negatives: 4
batch_size: 64
shuffle_data: True
n_epochs: 10
test_freq: 1
ckpt_freq: 1
device: 'cuda:0'
lr: 0.0001
# random_seed: 0
# random_seed: 1
random_seed: 8
apply_sigmoid: False
load_article_ids: False
contrastive_temperature: 0.08
contrastive_lambda: 0.1

# logging:
wandb: False
mode: offline
project: xnrs
tags: [mind, nrms]
name: mind_small_nrms_2
dir: /var/scratch/zta207/experiments
notes: NRMS model on MIND small dataset with full features
